### ISSUE TITLE
`repeat()` is not working

### ISSUE THREAD

**Issue by GeTechG** [monkin/glissade#1]
```rs
let animation: Box<dyn Animated<f32, Instant>> = Box::new(keyframes(0.0)
      .ease_to(1.0, Duration::from_secs_f32(1.0), Easing::Linear)
      .repeat()
      .run(Instant::now()));
...
animation.get(Instant::now())
```
The animation only plays once and that's it, I checked with `repeat_n()` and it works correctly so I think it's a bug.

**Comment by monkin** [comment]
Thank you for the report!

The problem was fixed here - https://github.com/monkin/glissade/pull/2.
The fixed version is already available at https://crates.io/crates/glissade/0.1.37.
